# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'coveralls'
Coveralls.wear!
require 'simplecov'
SimpleCov.start do
  add_filter '/spec/'
end

require 'rspec/its'

require 'queuel'
require 'aws-sdk'

Dir["./spec/support/**/*.rb"].sort.each {|f| require f}

RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.filter_run_excluding :perf

  config.mock_with(:rspec) { |c| c.syntax = [:expect, :should] }
  config.expect_with(:rspec) { |c| c.syntax = [:expect, :should] }

  config.before do
    Queuel.configure { log_level 5 }
  end

  config.include IntegrationHelpers, integration: true
  unless File.exist?(File.expand_path('../integration.yml', __FILE__))
    config.filter_run_excluding integration: true
  end

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end
